version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout:
          path: ~/repo
      
      - add_ssh_keys:
          fingerprints:
            - "SHA256:m9srz3elz7BkktLsfc+tcc3zQ3L5O4nPUuWJ3B87xOc"

      # Khôi phục bộ nhớ đệm của các dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # sử dụng bộ nhớ đệm mới nhất nếu không tìm thấy khớp chính xác
            - v1-dependencies-

      # Cài đặt dependencies
      - run:
          name: Install dependencies
          command: npm ci

      # Lưu bộ nhớ đệm của các dependencies
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # Chạy kiểm tra
      # - run:
      #     name: Run tests
      #     command: npm test:unit

      # Lưu kết quả kiểm tra
      # - store_test_results:
      #     path: test-results

      # Build ứng dụng
      - run:
          name: Build application
          command: npm run build

      # Lưu các sản phẩm build
      - store_artifacts:
          path: dist
  
  deploy:
    machine: 
      enabled: true
    steps:
      - run:
          name: Deploy over SSH
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'cd /home/docker/site/frontend-app && git fetch origin main && git pull origin main && git reset --hard origin/main && docker compose up -d --build frontend web-server'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main